on:
  push:
    branches:
      - feature/bogus
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
     FOLDER_NAME: changes/${{ github.repository }}/ ${{ github.head_ref || github.ref_name }}/$(date +%Y/%m/%d)
     FILE_NAME:  $(date +%H-%M-%S-%N).json
    steps:
      - uses: actions/checkout@v3
        with:
          repository: taarimalta/deleteThis
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "taarimalta@gmail.com"
      - name: Add new file
        run: |
          ls -al
          mkdir -p ${{ env.FOLDER_NAME }}
          cat >> ${{ env.FOLDERNAME }}/${{ env.FILENAME }} << 'END'
          {
          "committer": "${{ github.actor }}",
          "repository": "${{ github.repository }}",
          "updated_at": "${{ github.event.repository.updated_at}}",
          "branch": "${{ env.BRANCH_NAME }}"
          
          }
          END
          git add hello.txt
          git commit -m "hello added"
      - run: git push origin main
