on:
  push:
    branches:
      - feature/bogus
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: taarimalta/deleteThis
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "taarimalta@gmail.com"
      - name: Add new file
        run: |
          ls -al
          mkdir -p changes/${{ github.repository }}/$(date +%Y/%m/%d)
          cat >> $(date +%H-%M-%S-%N).json << 'END'
          {
          "committer": "${{ github.actor }}",
          "repository": "${{ github.repository }}",
          "updated_at": "${{ github.event.repository.updated_at}}"
          
          }
          END
          git add hello.txt
          git commit -m "hello added"
      - run: git push origin main
